# Generated by Django 4.0.2 on 2022-06-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_well_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='well_name',
            new_name='name',
        ),
    ]
