# Generated by Django 4.0.2 on 2022-06-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_created_by_alter_well_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='main.well')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_step', models.CharField(max_length=100)),
                ('first', models.BooleanField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_steps', to='main.phase')),
                ('previous_ops', models.ForeignKey(limit_choices_to={'name': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_steps', to='main.phase')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ops', to='main.step', unique=True)),
            ],
        ),
    ]
