# Generated by Django 4.0.2 on 2022-06-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phase_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='previous_ops',
            field=models.ForeignKey(limit_choices_to={'phase': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_steps', to='main.phase')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ops', to='main.step', unique=True),
        ),
    ]
