# Generated by Django 4.0.2 on 2022-06-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_step_previous_ops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='previous_ops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ops', to='main.step', unique=True),
        ),
    ]
