# Generated by Django 4.0.2 on 2022-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_step_previous_ops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='first',
        ),
        migrations.RemoveField(
            model_name='step',
            name='previous_ops',
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
