# Generated by Django 4.0.2 on 2022-06-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_step_first_remove_step_previous_ops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='main.phase')),
            ],
        ),
    ]
