# Generated by Django 4.0.2 on 2022-06-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_phase_order_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phase'),
        ),
        migrations.CreateModel(
            name='Lookahead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lookahead', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookaheads', to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='lookahead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='main.lookahead'),
        ),
    ]
