# Generated by Django 4.0.2 on 2022-06-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sequence_phase_lookahead_sequence_lookahead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['well', 'order']},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['lookahead', 'order']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['phase__well', 'phase__order', 'order']},
        ),
        migrations.AlterField(
            model_name='sequence',
            name='lookahead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='main.lookahead'),
        ),
    ]
