# Generated by Django 4.0.2 on 2022-06-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_project_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-last_modified']},
        ),
    ]
